version: '3.7'

configs:
  privileges:
    file: ./config/privilege.json
  conf:
    file: ./config/config.json

secrets:
  keys:
    file: ./config/keys.json

services:
  activityrankbot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: base
    volumes:
      - ./src:/usr/src/app/src
    container_name: ActivityRank-Bot.Dev
    command: npm run developmentNodemon
    configs:
      - privileges
      - conf
    secrets:
      - keys
