version: '3.7'

configs:
  privileges:
    file: ./config/privilege.json
  conf:
    file: ./config/config.json

secrets:
  keys:
    file: ./config/keys.json

services:
  activityrankbot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ActivityRank-Bot
    command: node dist/app.js
    configs:
      - privileges
      - conf
    secrets:
      - keys
